### ISSUE TITLE
Kpt render taking more time when there is large number of blueprints

### ISSUE THREAD

**Issue by sarathmohan4** [GoogleCloudPlatform/blueprints#136]
We could see a behaviour that the kpt fn render in the blueprint root directory is taking more time when there are large number of blueprints.

As kpt is git aware, is there any way that the render will happen only for the changed or newly created blueprints in the repository?
Or any other steps to improve the rendering stage performance as we are planning to provision large number of projects and resources through our gitops implementation. 

Please advise.

**Comment by bharathkkb** [comment]
Thanks for the report @sarathmohan4 
Since this is a kpt issue, I would recommend opening an issue here https://github.com/GoogleContainerTools/kpt

> As kpt is git aware, is there any way that the render will happen only for the changed or newly created blueprints in the repository?

AFAIK this is not currently supported within kpt.

> any other steps to improve the rendering stage performance

One possibility is if you have a flat structure with independent packages, you could script something where you git diff, find the top level folders that have changed and execute `kpt fn render $FOLDER`. Scripting parallel kpt execution maybe another possibility if you are running in a machine with more resources.

**Comment by morgante** [comment]
Yes, this is best addressed at the kpt level (feel free to open a new issue).

I know the team is already looking at improving function performance (tracking issue: https://github.com/GoogleContainerTools/kpt/issues/2469), but caching/fingerprinting is a good suggestion as well.

**Comment by sarathmohan4** [comment]
@bharathkkb Thanks for the reply. We tried with the git diff approach, and end up in a scenario which need separate handling for resource deletions. As only modified packages are rendered, and we cannot update the sync repo by completely removing all files (git rm), but  need to overwrite the rendered packages only in sync repo. 

This will not have any implicit knowledge of deleted resources. The deleted resources from the hydration repo will not get delete from the sync repo. Deletion of resources might need to handle separately.
