### ISSUE TITLE
org-id quirk in hierarchy from fn eval order

### ISSUE THREAD

**Issue by loudej** [GoogleCloudPlatform/blueprints#43]
The hierarchy blueprints have the `org-id` setter.yaml here:

https://github.com/GoogleCloudPlatform/blueprints/blob/07c398d254970eb982361db78402b5d8259c878f/catalog/hierarchy/team/Kptfile#L7-L11

https://github.com/GoogleCloudPlatform/blueprints/blob/07c398d254970eb982361db78402b5d8259c878f/catalog/hierarchy/team/setters.yaml#L7

Which seems to be designed for overridden by being nested in the landing zone:

https://github.com/GoogleCloudPlatform/blueprints/blob/07c398d254970eb982361db78402b5d8259c878f/catalog/landing-zone/setters.yaml#L14-L15

But the order of functions seems to be:
1. apply the hierarchy setter.yaml
2. expand the local-config `kind: ResourceHierarchy` into `kind: Folder` resources
3. apply the landing-zone setters.yaml

The effect is that the `ResourceHierarchy.spec.parentRef.external` always has the correct landing-zone `org-id`, but the derived top-level `Folder.spec.organizationRef.external` ends up with the placeholder value `'123456789012'`. It also shows up as an "permission denied" error once deployed so it took longer to figure out that I'd like to admit. :)

I believe the expected behavior would be for the `gcr.io/yakima-eap/generate-folders:latest` mutator to have written `external: '123456789012' # kpt-set: ${org-id}` to the top level `Folder`? That way it would be technically correct for the state of the files at step 2, but would also be updated with the final org-id at step 3.

**Comment by bharathkkb** [comment]
Thanks for the report @loudej, I was able to repro the issue. 
I believe we are switching to a manual edit of the RH yaml in https://github.com/GoogleCloudPlatform/blueprints/pull/41#discussion_r673521899

/cc @morgante

**Comment by morgante** [comment]
Indeed, the problem is that there's not currently any way in `kpt` to have the inner function (generate-folders) run *after* the outer function (applying top level setters). This is raised as a feature request: https://github.com/GoogleContainerTools/kpt/issues/2385

> I believe the expected behavior would be for the gcr.io/yakima-eap/generate-folders:latest mutator to have written external: '123456789012' # kpt-set: ${org-id} to the top level Folder?

Starting to pass comments around becomes very complex and isn't within the scope we want to have for individual functions (particularly since we would *not* want this comment to appear for nested folders.

For now, the workaround will be asking users to directly set the organization ID in `hierarchy.yaml`.
